const infoProductos = [

{   
    id: 1,
    precio: 6810,
    nombre:"Combativo",
    banda:"A.N.I.M.A.L.",
    genero:"Groove metal",
    categoria:"Cd",
    imgTapa:"./Assets/products/animalCombativo.jpg",
},
{
    id: 2,
    precio: 5450,
    nombre:"For Those That Wish To Exist",
    banda:"Architects",
    genero: "Metal progresivo",
    categoria:"Cd",
    imgTapa:"./Assets/products/architectsForThoseThatWishToExist.jpg",
},
{
    id: 3,
    precio:4950,
    nombre:"Colourmeinkindness",
    banda:"Basement",
    genero:"Rock alternativo",
    categoria:"Cd",
    imgTapa:"./Assets/products/basementColourmeinkindness.jpg",
},
{
    id: 4,
    precio:7000,
    nombre:"Libro - Basado En Hechos Reales",
    banda:"Carajo",
    genero:"Groove metal",
    categoria:"Cd",
    imgTapa:"./Assets/products/behrCarajo.webp",
},
{
    id: 5,
    precio:4900,
    nombre:"The Above",
    banda:"Code Orange",
    genero:"Rock alternativo",
    categoria:"Cd",
    imgTapa:"./Assets/products/CodeOrangeTheAbove.webp",
},
{
    id: 6,
    precio:75000,
    nombre:"Lost Not Forgotten Archives Made In Japan Live 2006",
    banda:"Dream Theater",
    genero:"Metal progresivo",
    categoria:"Vinilo",
    imgTapa:"./Assets/products/dreamTheaterLostNotForgottenArchivesMadeInJapanLive2006edVinylEdition.webp",
},
{
    id: 7,
    precio:20900,
    nombre:"The Doors",
    banda:"The Doors",
    genero:"Rock",
    categoria:"Vinilo",
    imgTapa:"./Assets/products/theDoorsVinilo.png",
},
{
    id: 8,
    precio:9400,
    nombre:"Huelas Digitales",
    banda:"Eruca Sativa",
    genero:"Rock alternativo",
    categoria:"Cd",
    imgTapa:"./Assets/products/erucaSativaHuellasDigitales.png",
},
{
    id: 9,
    precio:27500,
    nombre:"But here we are",
    banda:"Foo Fighters",
    genero:"Post-grunge",
    categoria:"Cd",
    imgTapa:"./Assets/products/fooFightersButHereWeAre.webp",
},
{
    id: 10,
    precio:2500,
    nombre:"EP - Convicciones",
    banda:"Horizontes HZT",
    genero:"Hard Core",
    categoria:"Cd",
    imgTapa:"./Assets/products/horizontesConvicciones.jpg",
},
{
    id: 11,
    precio:36800,
    nombre:"Crawler",
    banda:"Idles",
    genero:("Post-punk", "Post-hardcore"),
    categoria:"Vinilo",
    imgTapa:"./Assets/products/idlesCrawler.png",
},
{
    id: 12,
    precio:6500,
    nombre:"Furia Interior",
    banda:"Karma Sudaca",
    genero:"Rock alternativo",
    categoria:"Cd",
    imgTapa:"./Assets/products/karmaSudacafuriaInterior.webp",
},
{
    id: 13,
    precio:46600,
    nombre:"Requiem",
    banda:"Korn",
    genero:"Nu Metal",
    categoria:"Vinilo",
    imgTapa:"./Assets/products/kornRequiem.webp",
},
{
    id: 14,
    precio:10800,
    nombre:"IV",
    banda:"Led Zeppelin",
    genero:("Hard rock", "blues rock"),
    categoria:"Cd",
    imgTapa:"./Assets/products/ledZeppelinIv.png",
},
{
    id: 15,
    precio:8950,
    nombre:"Cassette - Led Zeppelin I",
    banda:"Led Zeppelin",
    genero:("Hard rock", "blues rock"),
    categoria:"Cassette",
    imgTapa:"./Assets/products/ledZeppelinIcassette.webp",
},
{
    id: 16,
    precio:69800,
    nombre:"Led Zeppelin III",
    banda:"Led Zeppelin",
    genero:("Hard rock", "blues rock"),
    categoria:"Vinilo",
    imgTapa:"./Assets/products/ledZeppelinIii.png",
},
{
    id: 17,
    precio:24100,
    nombre:"Chocolate Starfish & The Hot Dog Flavored Water",
    banda:"Limp Bizkit",
    genero:"Nu Metal",
    categoria:"Cd",
    imgTapa:"./Assets/products/limpBizkitChocolate.jpg",
},
{
    id: 18,
    precio:3000,
    nombre:"Amsterdam",
    banda:"Low Price",
    genero:"Rock Alternativo",
    categoria:"Cd",
    imgTapa:"./Assets/products/lowPriceAmsterdam.jpg",
},
{
    id: 19,
    precio:7700,
    nombre:"Absolution",
    banda:"Muse",
    genero:("Metal progresivo", "Rock Alternativo"),
    categoria:"Cd",
    imgTapa:"./Assets/products/museAbsolution.png",
},
{
    id: 20,
    precio:9500,
    nombre:"Live At Rome Olympic Stadium Cd Dvd",
    banda:"Muse",
    genero:("Metal progresivo", "Rock Alternativo"),
    categoria:"Cd",
    imgTapa:"./Assets/products/museLiveRome.jpg",
}
]